echo -debug ~/.config/kak/kakrc is being evaluated
%sh{
    # Given a list of root directories, recursively lists kak files under them,
    # so that for each file, only the first file with the same relative part
    # after its root is listed.
    list_unique_kak_files_in_directories_recursively() {
        find -L "$@" -type f -name '*\.kak' -printf "%H %P\n" \
            | sort --key=2,2 --stable \
            | uniq --skip-fields 1 \
            | tr ' ' '/'
    }

    autoload_unique_kak_files() {
        list_unique_kak_files_in_directories_recursively "$@" \
            | xargs -I '{}' printf 'try %%{ source "%s"\necho -debug Autoload: loaded "%s" } catch %%{ echo -debug Autoload: could not load "%s" }\n' '{}' '{}' '{}'
    }

    first="${kak_config}/autoload_override"
    second="${kak_runtime}/autoload"
    if [ -d "$first" ] && [ -d "$second" ]; then
        echo echo -debug "Autoload: loading unique files in order from the directories $first $second"
        autoload_unique_kak_files "$first" "$second"
    fi

    last="${kak_config}/finally.kak"
    if [ -f "$last" ]; then
        echo "source '$last'"
        echo echo -debug "Autoload: finally loaded $last"
    fi
}
